# Generated by Django 5.2.1 on 2025-05-25 19:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceGenreTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        help_text="Genre category name", max_length=50, unique=True
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        help_text="Voice ID to use for this genre", max_length=50
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        default=1.0, help_text="Speed multiplier to use for this genre"
                    ),
                ),
                (
                    "affect",
                    models.CharField(
                        blank=True,
                        help_text="Emotional affect for the voice",
                        max_length=50,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        help_text="Tone descriptor for the voice",
                        max_length=100,
                    ),
                ),
                (
                    "pacing",
                    models.CharField(
                        blank=True,
                        help_text="Pacing style for the voice",
                        max_length=50,
                    ),
                ),
                (
                    "pitch_variation",
                    models.CharField(
                        blank=True, help_text="Amount of pitch variation", max_length=50
                    ),
                ),
                (
                    "speaking_style",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the speaking style",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this genre category"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the template was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the template was last updated"
                    ),
                ),
            ],
            options={
                "ordering": ["genre"],
            },
        ),
        migrations.CreateModel(
            name="VoiceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        help_text="Tone category name.", max_length=50, unique=True
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        help_text="Voice ID to use for this tone.", max_length=50
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        default=1.0, help_text="Speed multiplier to use for this tone."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this tone category."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this mapping is active."
                    ),
                ),
            ],
            options={
                "ordering": ["tone"],
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="The name of the feed.", max_length=100),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique token for accessing the feed.",
                        unique=True,
                    ),
                ),
                (
                    "voice_mode",
                    models.CharField(
                        choices=[
                            ("single_default", "Single voice from defaults"),
                            ("single_custom", "Single voice from custom preset"),
                            ("auto", "Auto-generated voice"),
                        ],
                        default="single_default",
                        help_text="Voice mode preference for this feed",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the feed was created."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this feed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="The title of the article. Optional if URL is provided.",
                        max_length=255,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="The URL of the source article.",
                        max_length=2000,
                    ),
                ),
                (
                    "text_content",
                    models.TextField(
                        blank=True, help_text="The text content of the article."
                    ),
                ),
                (
                    "voice",
                    models.CharField(
                        choices=[
                            ("alloy", "Alloy"),
                            ("ash", "Ash"),
                            ("ballad", "Ballad"),
                            ("coral", "Coral"),
                            ("echo", "Echo"),
                            ("fable", "Fable"),
                            ("onyx", "Onyx"),
                            ("nova", "Nova"),
                            ("sage", "Sage"),
                            ("shimmer", "Shimmer"),
                            ("verse", "Verse"),
                        ],
                        default="alloy",
                        help_text="The voice to use for text-to-speech conversion.",
                        max_length=20,
                    ),
                ),
                (
                    "audio_file_path",
                    models.CharField(
                        blank=True, help_text="Path to the audio file.", max_length=255
                    ),
                ),
                (
                    "audio_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Unique identifier for the audio file.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Detailed error message if processing failed.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        help_text="The current status of the article.",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the article was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the article was last updated."
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the Celery task processing this article.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary of the article content.",
                        null=True,
                    ),
                ),
                (
                    "detected_tone",
                    models.CharField(
                        blank=True,
                        help_text="AI-detected tone of the article content.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "detected_genre",
                    models.CharField(
                        blank=True,
                        help_text="AI-detected genre of the article content.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        blank=True,
                        help_text="Voice ID used for text-to-speech conversion.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        blank=True,
                        help_text="Speed multiplier for text-to-speech conversion.",
                        null=True,
                    ),
                ),
                (
                    "multi_voice_data",
                    models.JSONField(
                        blank=True,
                        help_text="Stores structured data for multi-voice audio, including voice definitions and text segments.",
                        null=True,
                    ),
                ),
                (
                    "voice_parameters",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed voice parameters for text-to-speech conversion.",
                        null=True,
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        help_text="The feed this article belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="text_to_audio.feed",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenAIUsageStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        help_text="Number of tokens used in the request."
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        help_text="Processing time for the request in milliseconds."
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(help_text="Word count of the text processed."),
                ),
                (
                    "request_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the usage was recorded.",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="The article associated with this usage, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="text_to_audio.article",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who made the API request.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserVoicePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the voice preset.", max_length=100
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        help_text="Voice ID for this preset.", max_length=50
                    ),
                ),
                (
                    "speed",
                    models.FloatField(default=1.0, help_text="Speed for this preset."),
                ),
                (
                    "affect",
                    models.CharField(
                        blank=True,
                        help_text="Emotional affect for the voice",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        blank=True,
                        help_text="Tone descriptor for the voice",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "pacing",
                    models.CharField(
                        blank=True,
                        help_text="Pacing style for the voice",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "pitch_variation",
                    models.CharField(
                        blank=True,
                        help_text="Amount of pitch variation",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "speaking_style",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the speaking style",
                        null=True,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional prompt describing the desired speaking style.",
                    ),
                ),
                (
                    "sample_input",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional sample text used when designing the voice.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this preset."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the preset was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the preset was last updated."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this voice preset.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="feed",
            name="default_voice_preset",
            field=models.ForeignKey(
                blank=True,
                help_text="Voice preset to use for new articles in this feed by default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="text_to_audio.uservoicepreset",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="voice_preset",
            field=models.ForeignKey(
                blank=True,
                help_text="User-defined voice preset used for this article.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="text_to_audio.uservoicepreset",
            ),
        ),
        migrations.CreateModel(
            name="UserVoiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_voice",
                    models.CharField(
                        blank=True,
                        help_text="User's preferred TTS voice.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferred_speed",
                    models.FloatField(
                        default=1.0, help_text="User's preferred TTS speed multiplier."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the profile was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the profile was last updated."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user these voice preferences belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowedFeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The URL of the RSS feed to follow.", max_length=2000
                    ),
                ),
                (
                    "last_guid",
                    models.CharField(
                        blank=True,
                        help_text="The GUID of the last article processed from this feed. Used to avoid duplicates.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this feed was last checked for new articles.",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this followed feed is currently active and should be checked for updates.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this followed feed was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this followed feed was last updated.",
                    ),
                ),
                (
                    "destination_feed",
                    models.ForeignKey(
                        help_text="The destination feed where articles from this followed feed will be added.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_feeds",
                        to="text_to_audio.feed",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who is following this feed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "url", "destination_feed")},
            },
        ),
    ]
