"""Migration to add error_message field to Article and update Feed token.

This migration adds an error_message field to store detailed error information when
article processing fails, and updates the Feed token field constraints.
"""

# Generated by Django 5.2.1 on 2025-05-22 14:09

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration for adding error_message field to Article and updating Feed token."""

    dependencies = [
        ("text_to_audio", "0002_add_validation_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Detailed error message if processing failed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique token for accessing the feed.",
                unique=True,
            ),
        ),
    ]
