# Generated by Django 5.2.1 on 2025-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0003_article_error_message_alter_feed_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="text_content",
            field=models.TextField(
                blank=True, help_text="The text content of the article."
            ),
        ),
    ]
