# Generated by Django 5.2.1 on 2025-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0004_make_text_content_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The title of the article. Optional if URL is provided.",
                max_length=255,
            ),
        ),
    ]
