# Generated by Django 5.2.1 on 2025-05-24 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_audio', '0006_article_audio_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_used', models.IntegerField(help_text='Number of tokens used in the request.')),
                ('processing_time_ms', models.IntegerField(help_text='Processing time for the request in milliseconds.')),
                ('word_count', models.IntegerField(help_text='Word count of the text processed.')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the usage was recorded.')),
                ('article', models.ForeignKey(blank=True, help_text='The article associated with this usage, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='text_to_audio.article')),
                ('user', models.ForeignKey(help_text='The user who made the API request.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
