# Generated by Django 5.2.1 on 2025-05-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_audio', '0006_article_audio_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for audio generation.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the article was last updated.'),
        ),
    ]
