"""Migration to add article tracking fields for timeout detection."""

# Generated by Django 5.2.1 on 2025-05-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add Article model fields for timeout detection."""

    # Fields for tracking stale articles

    dependencies = [
        ("text_to_audio", "0007_openaiusagestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the article was last updated."
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="ID of the Celery task processing this article.",
                max_length=255,
                null=True,
            ),
        ),
    ]
