# Generated by Django 5.2.1 on 2025-05-25 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0009_article_summary"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        help_text="Tone category name.", max_length=50, unique=True
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        help_text="Voice ID to use for this tone.", max_length=50
                    ),
                ),
                (
                    "speed",
                    models.FloatField(
                        default=1.0, help_text="Speed multiplier to use for this tone."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this tone category."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this mapping is active."
                    ),
                ),
            ],
            options={
                "ordering": ["tone"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="detected_tone",
            field=models.CharField(
                blank=True,
                help_text="AI-detected tone of the article content.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="speed",
            field=models.FloatField(
                blank=True,
                help_text="Speed multiplier for text-to-speech conversion.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="voice_id",
            field=models.CharField(
                blank=True,
                help_text="Voice ID used for text-to-speech conversion.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UserVoiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_voice",
                    models.CharField(
                        blank=True,
                        help_text="User's preferred TTS voice.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "preferred_speed",
                    models.FloatField(
                        default=1.0, help_text="User's preferred TTS speed multiplier."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the profile was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the profile was last updated."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user these voice preferences belong to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
