# Generated by Django 5.2.1 on 2025-05-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "text_to_audio",
            "0010_voicemapping_article_detected_tone_article_speed_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserVoicePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the voice preset.", max_length=100
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        help_text="Voice ID for this preset.", max_length=50
                    ),
                ),
                (
                    "speed",
                    models.FloatField(default=1.0, help_text="Speed for this preset."),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of this preset."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the preset was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the preset was last updated."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this voice preset.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_presets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.AddField(
            model_name="article",
            name="voice_preset",
            field=models.ForeignKey(
                blank=True,
                help_text="User-defined voice preset used for this article.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="text_to_audio.uservoicepreset",
            ),
        ),
    ]
