# Generated by Django 5.2.1 on 2025-05-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_audio', '0010_voicemapping_article_detected_tone_article_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='multi_voice_data',
            field=models.JSONField(blank=True, help_text='Stores structured data for multi-voice audio, including voice definitions and text segments.', null=True),
        ),
    ]
