# Generated by Django 5.2.1 on 2025-05-25 15:37
"""Merge migration for divergence in migration history."""

from django.db import migrations


class Migration(migrations.Migration):
    """Merge migration class."""

    dependencies = [
        (
            "text_to_audio",
            "0010_voicemapping_article_detected_tone_article_speed_and_more",
        ),
        ("text_to_audio", "0011_article_multi_voice_data"),
        ("text_to_audio", "0011_uservoicepreset_article_voice_preset"),
    ]

    operations = []
