# Generated by Django 5.2.1 on 2025-05-25 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_audio', '0010_article_voice'),
        ('text_to_audio', '0011_article_multi_voice_data'),
        ('text_to_audio', '0011_uservoicepreset_article_voice_preset'),
    ]

    operations = [
    ]
