# Generated by Django 5.2.1 on 2025-05-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0012_fix_migration_conflicts"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="default_voice_preset",
            field=models.ForeignKey(
                blank=True,
                help_text="Voice preset to use for new articles in this feed by default.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="text_to_audio.uservoicepreset",
            ),
        ),
        migrations.AddField(
            model_name="uservoicepreset",
            name="prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional prompt describing the desired speaking style.",
            ),
        ),
        migrations.AddField(
            model_name="uservoicepreset",
            name="sample_input",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional sample text used when designing the voice.",
            ),
        ),
    ]
