# Generated by Django 5.2.1 on 2025-05-25 15:39
"""Final merge migration combining parallel branches."""

from django.db import migrations


class Migration(migrations.Migration):
    """Merge migration for diverging branches."""

    dependencies = [
        ("text_to_audio", "0013_fix_missing_voice_column"),
        ("text_to_audio", "0013_followedfeed"),
    ]

    operations = []
