# Generated by Django 5.2.1 on 2025-05-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0017_merge_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="voice",
            field=models.CharField(
                choices=[
                    ("alloy", "Alloy"),
                    ("ash", "Ash"),
                    ("ballad", "Ballad"),
                    ("coral", "Coral"),
                    ("echo", "Echo"),
                    ("fable", "Fable"),
                    ("onyx", "Onyx"),
                    ("nova", "Nova"),
                    ("sage", "Sage"),
                    ("shimmer", "Shimmer"),
                    ("verse", "Verse"),
                ],
                default="alloy",
                help_text="The voice to use for text-to-speech conversion.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feed",
            name="voice_mode",
            field=models.CharField(
                choices=[
                    ("single_default", "Single voice from defaults"),
                    ("single_custom", "Single voice from custom preset"),
                    ("auto", "Auto-generated voice"),
                ],
                default="auto",
                help_text="Voice mode preference for this feed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="uservoicepreset",
            name="voice_id",
            field=models.CharField(
                choices=[
                    ("alloy", "Alloy"),
                    ("ash", "Ash"),
                    ("ballad", "Ballad"),
                    ("coral", "Coral"),
                    ("echo", "Echo"),
                    ("fable", "Fable"),
                    ("onyx", "Onyx"),
                    ("nova", "Nova"),
                    ("sage", "Sage"),
                    ("shimmer", "Shimmer"),
                    ("verse", "Verse"),
                ],
                help_text="Voice ID for this preset.",
                max_length=50,
            ),
        ),
    ]
