# Generated by Django 5.2.1 on 2025-05-30 01:58

from django.db import migrations


def establish_voice_single_source_of_truth(apps, schema_editor):
    """
    Establish single source of truth for voice fields in Article model.

    Strategy:
    1. If both voice and voice_id are set:
       - If voice_id is a standard voice choice, clear voice_id and keep voice
       - If voice_id is custom (not in standard choices), clear voice and keep voice_id
    2. If only voice_id is set:
       - If voice_id is a standard voice choice, move to voice and clear voice_id
       - If voice_id is custom, clear voice (set to empty) and keep voice_id
    3. If only voice is set, keep as-is
    4. Log actions for transparency

    This ensures only one voice field contains data at a time.
    """
    Article = apps.get_model("text_to_audio", "Article")

    # Standard voice choices (from models.py VOICE_CHOICES)
    STANDARD_VOICES = {
        "alloy", "ash", "ballad", "coral", "echo",
        "fable", "onyx", "nova", "sage", "shimmer", "verse"
    }

    updated_count = 0
    conflict_count = 0

    for article in Article.objects.all():
        voice_is_set = bool(article.voice and str(article.voice).strip())
        voice_id_is_set = bool(article.voice_id and str(article.voice_id).strip())

        if voice_is_set and voice_id_is_set:
            # Conflict - both fields are set
            conflict_count += 1
            voice_id_lower = str(article.voice_id).lower().strip()

            if voice_id_lower in STANDARD_VOICES:
                # voice_id is standard, so prefer voice field and clear voice_id
                article.voice_id = None
                article.save(update_fields=['voice_id'])
                updated_count += 1
            else:
                # voice_id is custom, so prefer voice_id and clear voice
                article.voice = ""  # Clear voice for custom voice_id
                article.save(update_fields=['voice'])
                updated_count += 1

        elif not voice_is_set and voice_id_is_set:
            # Only voice_id is set
            voice_id_lower = str(article.voice_id).lower().strip()

            if voice_id_lower in STANDARD_VOICES:
                # Move standard voice_id to voice field
                article.voice = voice_id_lower
                article.voice_id = None
                article.save(update_fields=['voice', 'voice_id'])
                updated_count += 1
            else:
                # Keep custom voice_id, but ensure voice is empty
                if voice_is_set:  # Only update if voice was set
                    article.voice = ""
                    article.save(update_fields=['voice'])
                    updated_count += 1

    print(f"Voice field migration completed:")
    print(f"  - Found {conflict_count} articles with conflicting voice fields")
    print(f"  - Updated {updated_count} articles to establish single source of truth")
    print(f"  - Standard voices use 'voice' field")
    print(f"  - Custom voices use 'voice_id' field")


def reverse_establish_voice_single_source_of_truth(apps, schema_editor):
    """
    Reverse migration - this is a data migration so reversal is complex.
    We'll just log that this migration cannot be easily reversed.
    """
    print("WARNING: Reversing voice single source of truth migration")
    print("This migration modified data and cannot be automatically reversed.")
    print("Manual data restoration may be required if needed.")


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0018_alter_article_voice_alter_feed_voice_mode_and_more"),
    ]

    operations = [
        migrations.RunPython(
            establish_voice_single_source_of_truth,
            reverse_establish_voice_single_source_of_truth,
        ),
    ]
