# Generated by Django 5.2.1 on 2025-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0022_article_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="voice_id",
            field=models.CharField(
                blank=True,
                help_text="Custom voice ID for text-to-speech conversion. Use this field for custom or non-standard voices. Do not set both 'voice' and 'voice_id' - only one should be used. Leave empty when using standard voices.",
                max_length=50,
                null=True,
            ),
        ),
    ]
