# Generated by Django 5.2.1 on 2025-05-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0023_alter_article_voice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The title of the article. Optional if URL is provided.",
                max_length=1024,
            ),
        ),
    ]
