# Generated by Django 5.2.1 on 2025-06-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0024_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="processing_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about processing warnings, such as failed chunks in parallel TTS.",
                null=True,
            ),
        ),
    ]
