# Generated by Django 5.2.1 on 2025-06-04 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0026_add_cost_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openaiusagestats",
            options={"ordering": ["-request_timestamp"]},
        ),
        migrations.AlterField(
            model_name="openaiusagestats",
            name="estimated_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Estimated cost in USD for this operation.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="openaiusagestats",
            name="input_tokens",
            field=models.IntegerField(
                blank=True, help_text="Number of input tokens used.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="openaiusagestats",
            name="model_name",
            field=models.CharField(
                blank=True,
                default="gpt-4o-mini",
                help_text="The OpenAI model used for this operation.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="openaiusagestats",
            name="operation_type",
            field=models.CharField(
                choices=[("LLM", "Language Model"), ("TTS", "Text-to-Speech")],
                default="LLM",
                help_text="Type of operation performed.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="openaiusagestats",
            name="output_tokens",
            field=models.IntegerField(
                blank=True, help_text="Number of output tokens generated.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="openaiusagestats",
            name="tokens_used",
            field=models.IntegerField(
                help_text="Number of tokens used in the request (for backwards compatibility)."
            ),
        ),
        migrations.AddIndex(
            model_name="openaiusagestats",
            index=models.Index(
                fields=["user", "request_timestamp"],
                name="text_to_aud_user_id_d5abf8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="openaiusagestats",
            index=models.Index(
                fields=["article"], name="text_to_aud_article_9e9c59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="openaiusagestats",
            index=models.Index(
                fields=["operation_type"], name="text_to_aud_operati_2db4e5_idx"
            ),
        ),
    ]
