# Generated by Django 5.2.1 on 2025-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0027_alter_openaiusagestats_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="prompt",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Computed TTS prompt for audit/debugging purposes.",
                null=True,
            ),
        ),
    ]
