# Generated by Django 5.2.2 on 2025-06-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0028_alter_article_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaiusagestats",
            name="model_name",
            field=models.CharField(
                default="unknown",
                help_text="The OpenAI model used for the request.",
                max_length=100,
            ),
        ),
    ]
