# Generated by Django 5.2.1 on 2025-06-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0028_alter_article_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pdf", "PDF Document"),
                    ("html", "HTML Document"),
                    ("txt", "Text Document"),
                ],
                help_text="Type of uploaded file for processing.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="uploaded_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded PDF or HTML file to convert to audio.",
                null=True,
                upload_to="uploads/",
            ),
        ),
    ]
