# Generated by Django 5.2.3 on 2025-06-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0027_alter_openaiusagestats_options_and_more"),
        ("text_to_audio", "0029_add_model_name_to_openaiusagestats"),
    ]

    operations = []
