# Generated by Django 5.2.2 on 2025-06-06 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0027_alter_openaiusagestats_options_and_more"),
        ("text_to_audio", "0028_alter_article_prompt"),
    ]

    operations = []
