# Generated by Django 5.2.2 on 2025-06-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0030_merge_20250606_2335"),
    ]

    operations = []
