# Generated by Django 5.2.3 on 2025-06-26 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0030_add_fetch_full_text_to_followedfeed"),
        ("text_to_audio", "0031_merge_article_voice_display"),
    ]

    operations = []
