# Generated by Django 5.2.3 on 2025-07-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0032_merge_20250626_2317"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaiusagestats",
            name="model_name",
            field=models.CharField(
                default="unknown",
                help_text="The OpenAI model used for the request.",
                max_length=100,
            ),
        ),
    ]
