# Generated by Django 5.2.3 on 2025-07-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0033_alter_openaiusagestats_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="llm_provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("anthropic", "Anthropic Claude")],
                default="openai",
                help_text="LLM provider to use for content analysis and processing",
                max_length=20,
            ),
        ),
    ]
