# Generated by Django 5.2.3 on 2025-07-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0034_add_llm_provider_to_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaiusagestats",
            name="provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("anthropic", "Anthropic")],
                default="openai",
                help_text="The LLM provider used for the request.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="openaiusagestats",
            name="model_name",
            field=models.CharField(
                default="unknown",
                help_text="The model used for the request (e.g., gpt-4, claude-3-sonnet).",
                max_length=100,
            ),
        ),
    ]
