# Generated by Django 5.2.8 on 2025-11-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0035_add_tts_provider_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="voice",
            field=models.CharField(
                choices=[
                    ("alloy", "Alloy (OpenAI)"),
                    ("ash", "Ash (OpenAI)"),
                    ("ballad", "Ballad (OpenAI)"),
                    ("coral", "Coral (OpenAI)"),
                    ("echo", "Echo (OpenAI)"),
                    ("fable", "Fable (OpenAI)"),
                    ("onyx", "Onyx (OpenAI)"),
                    ("nova", "Nova (OpenAI)"),
                    ("sage", "Sage (OpenAI)"),
                    ("shimmer", "Shimmer (OpenAI)"),
                    ("en-US-Journey-D", "Journey-D (Gemini)"),
                    ("en-US-Journey-F", "Journey-F (Gemini)"),
                    ("en-US-Journey-O", "Journey-O (Gemini)"),
                    ("en-US-Chirp3-HD-Aoede", "Aoede (Chirp3-HD)"),
                    ("en-US-Chirp3-HD-Charon", "Charon (Chirp3-HD)"),
                    ("en-US-Chirp3-HD-Fenrir", "Fenrir (Chirp3-HD)"),
                ],
                default="alloy",
                help_text="Standard OpenAI TTS voice to use for conversion. Use this field for predefined voices (alloy, nova, etc.). Do not set both 'voice' and 'voice_id' - only one should be used.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="uservoicepreset",
            name="voice_id",
            field=models.CharField(
                choices=[
                    ("alloy", "Alloy (OpenAI)"),
                    ("ash", "Ash (OpenAI)"),
                    ("ballad", "Ballad (OpenAI)"),
                    ("coral", "Coral (OpenAI)"),
                    ("echo", "Echo (OpenAI)"),
                    ("fable", "Fable (OpenAI)"),
                    ("onyx", "Onyx (OpenAI)"),
                    ("nova", "Nova (OpenAI)"),
                    ("sage", "Sage (OpenAI)"),
                    ("shimmer", "Shimmer (OpenAI)"),
                    ("en-US-Journey-D", "Journey-D (Gemini)"),
                    ("en-US-Journey-F", "Journey-F (Gemini)"),
                    ("en-US-Journey-O", "Journey-O (Gemini)"),
                    ("en-US-Chirp3-HD-Aoede", "Aoede (Chirp3-HD)"),
                    ("en-US-Chirp3-HD-Charon", "Charon (Chirp3-HD)"),
                    ("en-US-Chirp3-HD-Fenrir", "Fenrir (Chirp3-HD)"),
                ],
                help_text="Voice ID for this preset.",
                max_length=50,
            ),
        ),
    ]
