# Generated by Django 5.2.3 on 2025-12-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_to_audio", "0037_add_audio_duration_to_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaiusagestats",
            name="provider",
            field=models.CharField(
                choices=[("openai", "OpenAI"), ("google", "Google")],
                default="openai",
                help_text="The API provider (e.g., 'openai', 'google').",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="openaiusagestats",
            index=models.Index(fields=["provider"], name="text_to_aud_provide_idx"),
        ),
        migrations.AlterField(
            model_name="openaiusagestats",
            name="model_name",
            field=models.CharField(
                default="unknown",
                help_text="The model or voice used for the request (e.g., 'gpt-4o-mini', 'en-US-Chirp3-HD-Orus').",
                max_length=100,
            ),
        ),
    ]
