# Generated by Django 5.2.4 on 2025-07-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GlobalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openai_api_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "openai_tts_model",
                    models.CharField(default="tts-1-hd", max_length=100),
                ),
                ("openai_tts_voice", models.CharField(default="alloy", max_length=50)),
                (
                    "firecrawl_api_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("use_firecrawl_by_default", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Global Configuration",
                "verbose_name_plural": "Global Configuration",
            },
        ),
    ]
