# Generated by Django 5.2.3 on 2025-07-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="default_tts_provider",
            field=models.CharField(
                default="openai",
                help_text="Default TTS provider (openai, google)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="enable_chunk_tone_llm",
            field=models.BooleanField(
                default=True,
                help_text="Enable ChunkTone LLM Service for advanced voice generation",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="max_analysis_words",
            field=models.PositiveIntegerField(
                default=8000,
                help_text="Maximum number of words to analyze for content analysis",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="openai_analysis_model",
            field=models.CharField(
                default="gpt-4.1",
                help_text="OpenAI model used for content analysis",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="openai_classification_model",
            field=models.CharField(
                default="gpt-4o-mini",
                help_text="OpenAI model used for genre classification",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="openai_title_model",
            field=models.CharField(
                default="gpt-4o-mini",
                help_text="OpenAI model used for generating article titles",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="openai_tts_response_format",
            field=models.CharField(
                default="wav",
                help_text="Audio response format from OpenAI TTS (mp3, opus, aac, flac, wav, pcm)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="podcast_image_url",
            field=models.URLField(
                blank=True,
                help_text="URL for the default podcast cover image",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="rss_external_hostname",
            field=models.CharField(
                blank=True,
                help_text="External hostname for RSS feeds (if different from site_url)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="site_url",
            field=models.URLField(
                default="http://localhost:8000",
                help_text="Base URL for the site, used in RSS feeds",
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="use_gpt_for_url_extraction",
            field=models.BooleanField(
                default=True, help_text="Use GPT for extracting article text from URLs"
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="firecrawl_api_key",
            field=models.CharField(
                blank=True,
                help_text="Firecrawl API key for advanced web scraping",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="openai_api_key",
            field=models.CharField(
                blank=True,
                help_text="Your OpenAI API key for text-to-speech and content analysis",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="openai_tts_model",
            field=models.CharField(
                default="tts-1-hd",
                help_text="OpenAI TTS model for generating speech (tts-1 or tts-1-hd)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="openai_tts_voice",
            field=models.CharField(
                default="alloy",
                help_text="Default OpenAI TTS voice (alloy, echo, fable, onyx, nova, shimmer)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="globalconfig",
            name="use_firecrawl_by_default",
            field=models.BooleanField(
                default=False,
                help_text="Use Firecrawl as the default web scraping service",
            ),
        ),
    ]
