# Generated by Django 5.2.3 on 2025-07-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appconfig", "0002_globalconfig_default_tts_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalconfig",
            name="anthropic_api_key",
            field=models.CharField(
                blank=True,
                help_text="Your Anthropic API key for Claude models",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="globalconfig",
            name="anthropic_model",
            field=models.CharField(
                default="claude-3-5-sonnet-20241022",
                help_text="Anthropic Claude model for content analysis and text processing",
                max_length=100,
            ),
        ),
    ]
